/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The networking mode, this container should operate in. One of BRIDGE|HOST|NONE|USER 
type AppAppContainerDockerNetwork struct {
}
