/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppHealthAppHealthCheck struct {

	Command AppHealthCommandCheck `json:"command,omitempty"`

	// Health check failures are ignored within this number of seconds of the task being started or until the task becomes healthy for the first time. 
	GracePeriodSeconds int32 `json:"gracePeriodSeconds,omitempty"`

	// Ignore HTTP 1xx responses
	IgnoreHttp1xx bool `json:"ignoreHttp1xx,omitempty"`

	// Number of seconds to wait between health checks
	IntervalSeconds int32 `json:"intervalSeconds,omitempty"`

	// Number of consecutive health check failures after which the unhealthy task should be killed. 
	MaxConsecutiveFailures int32 `json:"maxConsecutiveFailures,omitempty"`

	// Path to endpoint exposed by the task that will provide health status. Note: only used if protocol == HTTP[S].\" 
	Path string `json:"path,omitempty"`

	// The specific port to connect to. In case of dynamic ports, see portIndex. 
	Port AppNumberAnyPort `json:"port,omitempty"`

	// Index in this app's ports array to be used for health requests. An index is used so the app can use random ports, like [0, 0, 0] for example, and tasks could be started with port environment variables like $PORT1. 
	PortIndex AppNumberAnyPort `json:"portIndex,omitempty"`

	Protocol AppHealthAppHealthCheckProtocol `json:"protocol,omitempty"`

	// Number of seconds after which a health check is considered a failure regardless of the response. 
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`

	// Amount of time to wait until starting the health checks.
	DelaySeconds int32 `json:"delaySeconds,omitempty"`
}
