/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppUnreachableStrategyUnreachableEnabled struct {

	// If an instance is unreachable for longer than inactiveAfter seconds it is marked as inactive. This will trigger a new instance launch. The original task is not expunged yet. Must be less than expungeAfterSeconds.  The default value is set to 5 minutes (300 seconds). 
	InactiveAfterSeconds int64 `json:"inactiveAfterSeconds,omitempty"`

	// If an instance is unreachable for longer than unreachableExpungeAfter seconds it will be expunged.  That means it will be killed if it ever comes back. Instances are usually marked as unreachable before they are expunged but they don't have to. This value is required to be greater than inactiveAfterSeconds.  The default value is set to 10 minutes (600 seconds). 
	ExpungeAfterSeconds int64 `json:"expungeAfterSeconds,omitempty"`
}
