/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// v2 App defined constraints as a 2 or 3 element array with [fieldName, ConstraintOperator(,value?)]. 
type AppConstraintsAppConstraint struct {
}
