/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppHealthTcpHealthCheck struct {

	// The endpoint name to use. In \"host\" mode health checks use the hostPort. In other modes use the containerPort. 
	Endpoint StringsName `json:"endpoint"`
}
