/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppArtifactArtifact struct {

	Uri StringsUri `json:"uri"`

	Extract bool `json:"extract,omitempty"`

	Executable bool `json:"executable,omitempty"`

	Cache bool `json:"cache,omitempty"`

	DestPath StringsPath `json:"destPath,omitempty"`
}
