/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Credential to authenticate with the docker registry
type AppAppContainerDockerCredentials struct {

	// Principal to authenticate with the docker registry
	Principal string `json:"principal"`

	// Secret to authenticate with the docker registry
	Secret string `json:"secret,omitempty"`
}
