/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Information useful for service discovery
type AppNetworkIpDiscovery struct {

	// Array of objects describing the ports exposed by each task 
	Ports []AppNetworkIpDiscoveryPort `json:"ports,omitempty"`
}
