/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppConstraintsConstraint struct {

	FieldName string `json:"fieldName"`

	Operator AppConstraintsConstraintOperator `json:"operator"`

	Value string `json:"value,omitempty"`
}
