/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Docker's config.json. It should be specifed only as a secret name into a secret store, and the corresponding value should be a stringified valid JSON object which can be found in `~/.docker/config.json`. 
type AppAppContainerDockerDockerPullConfig struct {

	Secret string `json:"secret"`
}
