/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Port
type AppNetworkIpDiscoveryPort struct {

	// The port number
	Number AppNumberAnyPort `json:"number,omitempty"`

	// Name of the port
	Name StringsLegacyName `json:"name"`

	Protocol StringsNetworkProtocol `json:"protocol,omitempty"`

	Labels AppLabelKvLabels `json:"labels,omitempty"`
}
