/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppAppContainerAppCContainer struct {

	// The name of the AppC image to use
	Image string `json:"image"`

	// An image ID is a string of the format 'hash-value', where 'hash' is the hash algorithm used and 'value' is the hex-encoded digest. Currently the only permitted hash algorithm is sha512. 
	Id string `json:"id,omitempty"`

	// Optional labels. Suggested labels: 'version', 'os', 'arch'. 
	Labels AppLabelKvLabels `json:"labels,omitempty"`

	// The container will be pulled, regardless if it is already available on the local system 
	ForcePullImage bool `json:"forcePullImage,omitempty"`
}
