/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppHealthHealthCheck struct {

	Http AppHealthHttpHealthCheck `json:"http,omitempty"`

	Tcp AppHealthTcpHealthCheck `json:"tcp,omitempty"`

	// Command that executes some health check process. Use with pods requires Mesos v1.2 or higher. 
	Exec AppHealthCommandHealthCheck `json:"exec,omitempty"`

	// Health check failures are ignored within this number of seconds of the task being started or until the task becomes healthy for the first time. 
	GracePeriodSeconds int32 `json:"gracePeriodSeconds,omitempty"`

	// Interval between the health checks
	IntervalSeconds int32 `json:"intervalSeconds,omitempty"`

	// Number of consecutive failures until the task will be killed
	MaxConsecutiveFailures int32 `json:"maxConsecutiveFailures,omitempty"`

	// Amount of time to wait for the health check to complete.
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`

	// Amount of time to wait until starting the health checks.
	DelaySeconds int32 `json:"delaySeconds,omitempty"`
}
