/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppAppContainerContainer struct {

	Type_ AppAppContainerEngineType `json:"type"`

	Docker AppAppContainerDockerContainer `json:"docker,omitempty"`

	Appc AppAppContainerAppCContainer `json:"appc,omitempty"`

	Volumes []PodVolumesAppVolume `json:"volumes,omitempty"`

	// Map container ports to host and service ports when using bridge- or container-mode networking. If left unspecified, Marathon will provide a single, default port mapping. To obtain a container with no port mappings, specify an empty array here. 
	PortMappings []AppAppContainerContainerPortMapping `json:"portMappings,omitempty"`
}
