/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppNetworkPortDefinition struct {

	// If requirePorts is set to true, then this port number will be used on the agent host. Otherwise if the requirePorts is set to false and this port number is not zero, then it will be used as a service port and a dynamic port will be used on the agent host. If it is set to zero, a dynamic port will be used on the host and a unique service port will be assigned by Marathon. 
	Port AppNumberAnyPort `json:"port,omitempty"`

	Labels AppLabelKvLabels `json:"labels,omitempty"`

	// Name of the service hosted on this port. If provided, it must be unique over all port definitions. 
	Name StringsLegacyName `json:"name,omitempty"`

	// If this port is used for tcp or udp or both.
	Protocol StringsNetworkProtocol `json:"protocol,omitempty"`
}
