/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppAppContainerDockerParameter struct {

	// key of this parameter
	Key string `json:"key"`

	// value of this parameter
	Value string `json:"value"`
}
