/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// If an application definition includes the 'ipAddress' field, then Marathon will request a per-task IP from Mesos. A separate ports/portMappings configuration is then disallowed. 
type AppNetworkIpAddress struct {

	// DEPRECATED. Please try to use portMappings instead. 
	Discovery AppNetworkIpDiscovery `json:"discovery,omitempty"`

	// Ignored by Marathon, only exists here to preserve API compat (for now).
	Groups []string `json:"groups,omitempty"`

	Labels AppLabelKvLabels `json:"labels,omitempty"`

	// If present, declares the name of the network that the container should join. In practice it is up to the IPAM to decide how to interpret this field 
	NetworkName string `json:"networkName,omitempty"`
}
