/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Constrain which volume to choose on the agent. Currently, it is only possible to constrain the path of the disk resource by regular expression. 
type AppConstraintsVolumeConstraint struct {
}
