/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// `container` networks are named networks and are assigned an IP address by Mesos. The `container/bridge` network is a special container network that operates in a manner similar to Docker's \"default bridge\" mode, and depends on specific Mesos CNI support. The `host` network results in containers sharing the network namespace of the Mesos agent, and no IP address is allocated. 
type AppNetworkNetworkMode struct {
}
