/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// When using local persistent volumes that pin tasks onto agents, these values define how Marathon handles terminal states of these tasks. 
type AppAppResidency struct {

	// When a task using persistent local volumes cannot be restarted on the agent it's been pinned to, Marathon will try to launch this task on another node after this timeout. Defaults to 3600 (one hour).\", 
	RelaunchEscalationTimeoutSeconds int64 `json:"relaunchEscalationTimeoutSeconds"`

	TaskLostBehavior StringsTaskLostBehavior `json:"taskLostBehavior"`
}
