/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Endpoints accept connections from outside of a pod. Endpoints may also be advertised outside of a cluster. 
type AppNetworkEndpoint struct {

	// Name of this port. Should be unique in the context of the pod. 
	Name StringsName `json:"name"`

	// The container port that a task's process is actually listening on. Required if the network mode is container 
	ContainerPort AppNumberPort `json:"containerPort,omitempty"`

	// Mapped port on the host. All host ports are allocated from resource offers. 
	HostPort AppNumberAnyPort `json:"hostPort,omitempty"`

	// The protocol of this port, advertised in Mesos DiscoveryInfo (DI). Specifying more than one protocol here will result in the generation of multiple Port DI entries. 
	Protocol []StringsName `json:"protocol,omitempty"`

	// Metadata as key/value pair. Possible uses include VIPs, per-network-interface binding 
	Labels AppLabelKvLabels `json:"labels,omitempty"`

	// List of the container networks associated with this endpoint. If absent, then this endpoint is associated with all defined container networks (for this application). A single item list is mandatory when `hostPort` is specified and multiple container networks are defined. 
	NetworkNames []StringsName `json:"networkNames,omitempty"`
}
