/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppNetworkNetwork struct {

	// Defines the name of the container network to join. Not for use with `host` mode networking. 
	Name StringsName `json:"name,omitempty"`

	Mode AppNetworkNetworkMode `json:"mode,omitempty"`

	// Labels applied to the pod's NetworkInfo. Ignored when using `host` node networking. 
	Labels AppLabelKvLabels `json:"labels,omitempty"`
}
