/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type AppHealthCommandShellCommand struct {

	// command line executed by the default shell, not parsed by marathon 
	Shell string `json:"shell"`
}
