/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// Group is used to create or update applications and groups. Pods are not mutable through this interface, but are included for completeness. 
type GroupGroup struct {

	Id StringsPathId `json:"id"`

	Apps []AppApp `json:"apps,omitempty"`

	Pods []PodPod `json:"pods,omitempty"`

	// Groups can build a tree. Each group can contain sub-groups. The sub-groups are defined here. 
	Groups []GroupGroup `json:"groups,omitempty"`

	// A list of services that this group depends on. An order is derived from the dependencies for performing start/stop and upgrade of the application. For example, an application /a relies on the services /b which itself relies on /c. To start all 3 applications, first /c is started than /b than /a. 
	Dependencies []StringsPathId `json:"dependencies,omitempty"`

	Version time.Time `json:"version,omitempty"`
}
