/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type LoggingLoggerChange struct {

	// The log level to set.
	Level LoggingLoggerLevel `json:"level"`

	// The full qualified name of the logger.
	Logger string `json:"logger"`

	// The number of seconds to set this logging level. The current logging level is reset after the duration. If this parameter is not defined, the change to the logging level is permanent 
	DurationSeconds int32 `json:"durationSeconds,omitempty"`
}
