/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type MetricsMetrics struct {

	Start time.Time `json:"start"`

	End time.Time `json:"end"`

	Histograms map[string]MetricsHistogram `json:"histograms"`

	Counters map[string]MetricsCounter `json:"counters"`

	Gauges map[string]MetricsHistogram `json:"gauges"`

	MinMaxCounter map[string]MetricsHistogram `json:"min-max-counter"`
}
