/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type MetricsCounter struct {

	// The current value
	Count int64 `json:"count"`

	// metadata about the metric
	Tags map[string]string `json:"tags"`

	// The unit of measurement
	Unit MetricsUnitOfMeasurement `json:"unit"`
}
