/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type PodStatusStatusCondition struct {

	// Human and machine-readable name of this condition. For example \"healthy\", \"disk-full\". 
	Name StringsName `json:"name"`

	// last time the value field was changed for this condition
	LastChanged time.Time `json:"lastChanged"`

	// last time this condition was updated (value may not have changed)
	LastUpdated time.Time `json:"lastUpdated"`

	// the state of the condition. may be boolean or some enumeration-derived value
	Value string `json:"value"`

	// a machine-readable value that systems use to reason about the state of the condition 
	Reason string `json:"reason,omitempty"`
}
