/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodVolumesAppExternalVolume struct {

	// The path of the volume in the container
	ContainerPath string `json:"containerPath"`

	External PodVolumesExternalVolume `json:"external"`

	// Possible values are RO for ReadOnly and RW for Read/Write
	Mode StringsReadMode `json:"mode"`
}
