/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodStatusContainerTerminationState struct {

	ExitCode int32 `json:"exitCode,omitempty"`

	// Human-explanation for container termination.
	Message string `json:"message,omitempty"`
}
