/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodVolumesHostVolume struct {

	// The name of the volume to reference.
	Name StringsName `json:"name"`

	// Absolute path of the file or directory on the agent, or else the relative path of the directory in the executor's sandbox. Host volumes are useful for mapping directories that exist on the agent apriori, or within the executor sandbox. No resources (Mesos or otherwise) are allocated for these types of volumes. 
	Host string `json:"host"`
}
