/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// DEGRADED - The number of STABLE pod instances is less than the number of desired instances. STABLE   - All launched pod instances have started and, if health checks were specified, are all healthy. TERMINAL - Marathon is tearing down all of the instances for this pod. 
type PodStatusPodState struct {
}
