/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type PodStatusContainerStatus struct {

	// name of the container specification (within the pod)
	Name StringsName `json:"name"`

	Status PodStatusContainerState `json:"status"`

	// Time at which the status code was last modified. 
	StatusSince time.Time `json:"statusSince"`

	// Human-friendly explanation for the container's current status. 
	Message string `json:"message,omitempty"`

	// Set of status conditions that apply to this container. 
	Conditions []PodStatusStatusCondition `json:"conditions,omitempty"`

	// Unique ID of this container in the cluster. TODO(jdef) Probably represents the Mesos task ID. 
	ContainerId string `json:"containerId,omitempty"`

	Endpoints []PodStatusContainerEndpointStatus `json:"endpoints,omitempty"`

	// Resources in use by this container. 
	Resources PodResourcesResources `json:"resources,omitempty"`

	Termination PodStatusContainerTerminationState `json:"termination,omitempty"`

	// Time that this status was last checked and updated (even if nothing changed) 
	LastUpdated time.Time `json:"lastUpdated"`

	// Time that this status was last modified (some aspect of status did change) 
	LastChanged time.Time `json:"lastChanged"`
}
