/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// PENDING  - Instance is queued for launch. STAGING  - Instance has been launched but is not yet running. STABLE   - Any terminated containers have completed successfully and any running containers            are healthy (TBD by health checks, if enabled). DEGRADED - One or more containers are running but the instance is not considered STABLE. TERMINAL - Instance is in the process of shutting down. 
type PodStatusPodInstanceState struct {
}
