/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodVolumesPersistentVolume struct {

	Type_ PodVolumesPersistentVolumeType `json:"type,omitempty"`

	// The size of the persistence volume in MB.
	Size int64 `json:"size"`

	// For `mount` mesos disk resources, the optional maximum size of an exclusive mount volume to be considered. 
	MaxSize int64 `json:"maxSize,omitempty"`

	// Constraints restricting where new persistent volumes should be created. Currently, it is only possible to constrain the path of the disk resource by regular expression. 
	Constraints []AppConstraintsVolumeConstraint `json:"constraints,omitempty"`
}
