/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodStatusContainerTerminationHistory struct {

	ContainerId string `json:"containerId"`

	LastKnownState PodStatusContainerState `json:"lastKnownState,omitempty"`

	Termination PodStatusContainerTerminationState `json:"termination,omitempty"`
}
