/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Mesos Container
type PodContainerPodContainer struct {

	// The name of this container
	Name StringsName `json:"name"`

	Exec PodContainerMesosExec `json:"exec,omitempty"`

	// The resources to allocate to the container.
	Resources PodResourcesResources `json:"resources"`

	// The ports needed to run this container
	Endpoints []AppNetworkEndpoint `json:"endpoints,omitempty"`

	// The filesystem image to populate the container with
	Image PodContainerImage `json:"image,omitempty"`

	Environment AppEnvEnvVars `json:"environment,omitempty"`

	// The OS user to use to run the tasks on the agent. Values here override a \"user\" value specified in the pod definition. 
	User string `json:"user,omitempty"`

	// All healthchecks to perform on the container
	HealthCheck AppHealthHealthCheck `json:"healthCheck,omitempty"`

	// All volume mounts
	VolumeMounts []PodVolumesVolumeMount `json:"volumeMounts,omitempty"`

	// All artifacts to download before the task runs
	Artifacts []AppArtifactArtifact `json:"artifacts,omitempty"`

	// Metadata as key/value pair. Useful when passing directives to be interpreted by Mesos modules. 
	Labels AppLabelKvLabels `json:"labels,omitempty"`

	Lifecycle PodContainerLifecycle `json:"lifecycle,omitempty"`

	// Describes the information about (pseudo) TTY that can be attached to the process of this container. 
	Tty AppContainerCommonsTty `json:"tty,omitempty"`
}
