/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Add new possible super-types as different scaling policies are supported. 
type PodPodScalingPolicy struct {

	Kind PodPodScalingPolicyType `json:"kind"`
}
