/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// A pod allows one to launch a collection co-located (on the same agent) containers that share the same network namespace and that may share the same volumes. Resources are specified on a per-container basis. 
type PodPod struct {

	Id StringsPathId `json:"id"`

	// Metadata as key/value pair. Useful when passing directives to be interpreted by Mesos modules. 
	Labels AppLabelKvLabels `json:"labels,omitempty"`

	// The version of the definition, immutable
	Version time.Time `json:"version,omitempty"`

	// The OS user to use to run the tasks on the agent. May be overridden by a container. 
	User string `json:"user,omitempty"`

	// Environment Variables to set at the pod level. Individual containers may override them 
	Environment AppEnvEnvVars `json:"environment,omitempty"`

	Containers []PodContainerPodContainer `json:"containers"`

	Secrets AppSecretsSecrets `json:"secrets,omitempty"`

	// Volumes defined on a pod level that are mounted into containers
	Volumes []PodVolumesPodVolume `json:"volumes,omitempty"`

	// Network settings are defined on a pod level. All containers share the same network stack. At this time, only one stack is supported. 
	Networks []AppNetworkNetwork `json:"networks,omitempty"`

	Scaling PodPodScalingPolicy `json:"scaling,omitempty"`

	Scheduling PodPodSchedulingPolicy `json:"scheduling,omitempty"`

	// The resources to allocate to the executor.
	ExecutorResources PodResourcesExecutorResources `json:"executorResources,omitempty"`
}
