/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// Pod status communicates the lifecycle phase of the pod, current instance and container status, and recent termination status history. 
type PodStatusPodStatus struct {

	Id StringsPathId `json:"id"`

	// The latest version of the pod specification (that has the same pod ID). 
	Spec PodPod `json:"spec"`

	Status PodStatusPodState `json:"status"`

	// Time at which the status code was last modified. 
	StatusSince time.Time `json:"statusSince"`

	// Human-friendly explanation for reason of the current status. 
	Message string `json:"message,omitempty"`

	Instances []PodStatusPodInstanceStatus `json:"instances,omitempty"`

	// List of most recent instance terminations. TODO(jdef) determine how many items might show up here; current thinking is .. not many 
	TerminationHistory []PodStatusTerminationHistory `json:"terminationHistory,omitempty"`

	// Time that this status object was last checked and updated (even if nothing changed) 
	LastUpdated time.Time `json:"lastUpdated"`

	// Time that this status object was last modified (some aspect of status did change) 
	LastChanged time.Time `json:"lastChanged"`
}
