/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodStatusNetworkStatus struct {

	// name of the network
	Name StringsName `json:"name,omitempty"`

	Addresses []string `json:"addresses,omitempty"`
}
