/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodVolumesPodSecretVolume struct {

	// Name of the pod level volume
	Name string `json:"name"`

	// References the secret that is used by this volume
	Secret string `json:"secret"`
}
