/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodPodSchedulingPolicy struct {

	Backoff PodPodSchedulingBackoffStrategy `json:"backoff,omitempty"`

	Upgrade PodPodUpgradeStrategy `json:"upgrade,omitempty"`

	Placement PodPodPlacementPolicy `json:"placement,omitempty"`

	KillSelection AppKillSelectionKillSelection `json:"killSelection,omitempty"`

	UnreachableStrategy AppUnreachableStrategyUnreachableStrategy `json:"unreachableStrategy,omitempty"`
}
