/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Executor Resource Allocations. Same as Resources but reserved for the pod executor.
type PodResourcesExecutorResources struct {

	// The number of CPU shares this pod needs per instance for its executor. This number does not have to be integer, but can be a fraction.
	Cpus float64 `json:"cpus,omitempty"`

	// The amount of memory in MB that is needed for the pod instance for the pod instance's executor
	Mem float64 `json:"mem,omitempty"`

	// How much disk space is needed for for the executor. This number does not have to be an integer, but can be a fraction.
	Disk float64 `json:"disk,omitempty"`
}
