/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodContainerMesosExec struct {

	// Command specification executed by Mesos, not parsed by Marathon. The presence of `command.shell` implies `overrideEntrypoint=true`. 
	Command AppHealthCommandMesosCommand `json:"command"`

	// When true argv[0] will be used as the entrypoint/exec of the container. Otherwise the contents of argv[] are appended as arguments. 
	OverrideEntrypoint bool `json:"overrideEntrypoint,omitempty"`
}
