/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodVolumesExternalVolume struct {

	// The size of the external volume in GiB
	Size int64 `json:"size,omitempty"`

	// The name of the volume
	Name string `json:"name,omitempty"`

	// The name of the volume provider
	Provider string `json:"provider,omitempty"`

	// Provider specific volume configuration options
	Options AppLabelKvLabels `json:"options,omitempty"`
}
