/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodContainerLifecycle struct {

	// After a SIGTERM is sent to a container instance, Mesos will wait this number of seconds before issuing a SIGKILL. 
	KillGracePeriodSeconds float64 `json:"killGracePeriodSeconds,omitempty"`
}
