/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PodContainerImage struct {

	Kind PodContainerImageType `json:"kind"`

	// address/identifier of the file system image
	Id StringsPath `json:"id"`

	// Name of a secret whose value contains a stringified Docker config.json 
	PullConfig AppAppContainerDockerDockerPullConfig `json:"pullConfig,omitempty"`

	// true if the image should always be pulled
	ForcePull bool `json:"forcePull,omitempty"`

	// Used during image discovery and dependency resolution. Several well-known labels are defined: version: the version of this image os: (default: linux) operating system arch: (default: amd64) architecture 
	Labels AppLabelKvLabels `json:"labels,omitempty"`
}
