/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type PodStatusTerminationHistory struct {

	InstanceID string `json:"instanceID"`

	StartedAt time.Time `json:"startedAt"`

	TerminatedAt time.Time `json:"terminatedAt"`

	// Human-friendly explanation for termination. 
	Message string `json:"message,omitempty"`

	Containers []PodStatusContainerTerminationHistory `json:"containers,omitempty"`
}
