/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type QueueQueueDelay struct {

	// The number of seconds to wait, before the next launch attempt is started.
	TimeLeftSeconds float32 `json:"timeLeftSeconds"`

	// true, if this run spec is backed off. Otherwise false.
	Overdue bool `json:"overdue"`
}
