/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type QueueOfferAgentAttribute struct {

	// The name of the attribute.
	Name string `json:"name"`

	// The text value of this attribute
	Text string `json:"text,omitempty"`

	// The scalar value of the attribute.
	Scalar float32 `json:"scalar,omitempty"`

	// The range value of the attribute.
	Ranges []QueueOfferNumberRange `json:"ranges,omitempty"`

	// all values of this attribute.
	Set []string `json:"set,omitempty"`
}
