/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type QueueOfferOfferResource struct {

	// The name of the resource.
	Name string `json:"name"`

	// The role this resource is assigned to.
	Role string `json:"role"`

	// The scalar value of the resource.
	Scalar float64 `json:"scalar,omitempty"`

	// The range value of the resource.
	Ranges []QueueOfferNumberRange `json:"ranges,omitempty"`

	// all values of this resource.
	Set []string `json:"set,omitempty"`
}
