/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type QueueProcessedOffersSummary struct {

	// The number of processed offers for this launch attempt.
	ProcessedOffersCount float32 `json:"processedOffersCount"`

	// The number of unused offers for this launch attempt.
	UnusedOffersCount float32 `json:"unusedOffersCount"`

	// Point in time when the last unused offer has been processed.
	LastUnusedOfferAt time.Time `json:"lastUnusedOfferAt,omitempty"`

	// Point in time when the last used offer has been processed.
	LastUsedOfferAt time.Time `json:"lastUsedOfferAt,omitempty"`

	// Summarizes the reasons for not using offers for all last offers. This summary accumulates all processed offers by only taking the last offer per agent into account. 
	RejectSummaryLastOffers []QueueDeclinedOfferStep `json:"rejectSummaryLastOffers,omitempty"`

	// Summarizes the reasons for not using offers for the launch attempt of this run specification. This summary accumulates all processed offers since the start of the launch attempt. 
	RejectSummaryLaunchAttempt []QueueDeclinedOfferStep `json:"rejectSummaryLaunchAttempt,omitempty"`
}
