/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type QueueDeclinedOfferStep struct {

	Reason string `json:"reason"`

	Declined float32 `json:"declined"`

	Processed float32 `json:"processed"`
}
