/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type QueueQueueApp struct {

	// The number of instances left to launch.
	Count float32 `json:"count"`

	// If a runspec has failed to often the launch will be delayed. See backoff to tune this behavior.
	Delay QueueQueueDelay `json:"delay,omitempty"`

	// point in time since Marathon has started to launch tasks.
	Since time.Time `json:"since"`

	// Statistics for processed offers.
	ProcessedOffersSummary QueueProcessedOffersSummary `json:"processedOffersSummary"`

	// Last N unused offers, where N can be configured via xxx.
	LastUnusedOffers []QueueUnusedOffer `json:"lastUnusedOffers,omitempty"`

	App AppApp `json:"app"`
}
