/* 
 * Marathon REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type QueueUnusedOffer struct {

	// The offer that could not be used.
	Offer QueueOfferOffer `json:"offer"`

	// The reasons why this offer can not be used.
	Reason []string `json:"reason"`

	// when this offer has been processed
	Timestamp time.Time `json:"timestamp"`
}
